## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [2]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [44]:
# Type your solution here
import numpy as np
import pandas as pd

# 1-1
df = pd.DataFrame(data)
print(df)

# 1-2
group1 = df[((df.job == "psychologist") | (df.job == "teacher")&((df['num_cars'])>(df['family_size'])))]
print(group1)

# 1-3
group2 = df.loc[(df.family_size<=2) & (df.num_cars>=1)]
print(group2)

# 1-4
print(df['job'].unique())

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1
    name           job  family_size  num_cars
1  Jacob  psychologist            2         1
4   Ryan  psychologist            2         2
5   Lisa  psychologist            3         4
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1
['teacher' 'psychologist' 'data scientist' 'software developer']


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [41]:
import numpy as np
import pandas as pd
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 11)) #changed from 10 to 11
weights = pd.Series(np.linspace(1, 10, 10))

In [42]:
# Type your solution here

# Get fruit-weight pairs by fruit
# fruit_weights = pd.Series(fruit, index=weights)

# Use "group by" and "mean" functions
print(weights.groupby(fruit).mean())
# print(np.average(fruit_weights['apple']))

apple     2.5
banana    8.0
carrot    6.5
dtype: float64


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [29]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [39]:
# Type your solution here

# 3-1

# MANUAL SOLUTION
# sorted_courses = np.sort(course_name)
# selection = input("Enter a course name: ")
# while selection not in sorted_courses:
#   selection = input("Enter a course name: ")
# print(np.where(sorted_courses==selection))

# NUMPY SOLUTION
indices = np.argsort(course_name) 
print(indices) 

# 3-2

# MANUAL SOLUTION
# for e in course_name:
#   if e[0] == "P" or e[0] == "p":
#     print(e, "starts with \'P\'")
#   else:
#     print(e, "doesn't start with a \'P\'")

# NUMPY SOLUTION
startsWithP = np.char.startswith(course_name, "P")
print(startsWithP)

[1 3 0 2 4]
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [37]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [38]:
# Type your solution here

# 4-1
print("Original:", student_id)
print("Reversed:", np.flip(student_id))

# 4-2
sorted_ids = np.sort(student_id)
# print(sorted_ids)
print("Largest 3 values:", sorted_ids[-3:])

Original: [1023 5202 6230 1671 1682 5241 4532]
Reversed: [4532 5241 1682 1671 6230 5202 1023]
Largest 3 values: [5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [35]:
# Type your solution here
import numpy as np

# Hint: you can use arange to start off
arr3 = np.arange(0,101,3)
arr5 = np.arange(0,101,5)
both = np.concatenate((arr3, arr5))
unique = np.unique(both)
print(unique)
print("Sum =", unique.sum())

[  0   3   5   6   9  10  12  15  18  20  21  24  25  27  30  33  35  36
  39  40  42  45  48  50  51  54  55  57  60  63  65  66  69  70  72  75
  78  80  81  84  85  87  90  93  95  96  99 100]
Sum = 2418


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [33]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
# Type your solution here
# 6-1
arr[:,[1,2]] = arr[:,[2,1]] # what's the explanation behind this syntax?
print("Swapped column 1 with column 2:")
print(arr)

#6-2
arr[[0,1],:] = arr[[1,0],:]
print("Swapped row 0 with row 1:")
print(arr)



Swapped column 1 with column 2:
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
Swapped row 0 with row 1:
[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
